// AXI-Stream Master Test Sequences (High-Fidelity)
// Generated by uvm_generator skill Pass 2

// TC_MST_001: Single-beat transfer
class axi_stream_master_tc_mst_001_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_001_seq)
  function new(string name = "axi_stream_master_tc_mst_001_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { tlast == 1; tkeep == '1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_002: Zero-delay burst (Multi-beat)
class axi_stream_master_tc_mst_002_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_002_seq)
  function new(string name = "axi_stream_master_tc_mst_002_seq"); super.new(name); endfunction
  task body();
    for (int i=0; i<10; i++) begin
      req = axi_stream_master_seq_item::type_id::create("req");
      start_item(req);
      if(!req.randomize() with { delay_cycles == 0; tlast == (i==9); }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_003: Negative - TVALID drop before TREADY
class axi_stream_master_tc_mst_003_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_003_seq)
  function new(string name = "axi_stream_master_tc_mst_003_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { drop_valid_early == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_004: 4-stream Interleaving
class axi_stream_master_tc_mst_004_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_004_seq)
  function new(string name = "axi_stream_master_tc_mst_004_seq"); super.new(name); endfunction
  task body();
    for (int i=0; i<20; i++) begin
      req = axi_stream_master_seq_item::type_id::create("req");
      start_item(req);
      if(!req.randomize() with { tid == (i%4); tlast == (i >= 16); }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_005: Sparse stream (100 beats as per plan)
class axi_stream_master_tc_mst_005_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_005_seq)
  function new(string name = "axi_stream_master_tc_mst_005_seq"); super.new(name); endfunction
  task body();
    repeat(100) begin
      req = axi_stream_master_seq_item::type_id::create("req");
      start_item(req);
      if(!req.randomize()) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_006: Illegal Qualifier (TSTRB=1, TKEEP=0)
class axi_stream_master_tc_mst_006_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_006_seq)
  function new(string name = "axi_stream_master_tc_mst_006_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { tkeep == 4'b1110; tstrb == 4'b1111; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_007: Null packet termination
class axi_stream_master_tc_mst_007_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_007_seq)
  function new(string name = "axi_stream_master_tc_mst_007_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { tlast == 1; tkeep == 0; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_008: Async reset mid-transfer
class axi_stream_master_tc_mst_008_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_008_seq)
  function new(string name = "axi_stream_master_tc_mst_008_seq"); super.new(name); endfunction
  task body();
    for (int i=0; i<5; i++) begin
      req = axi_stream_master_seq_item::type_id::create("req");
      start_item(req);
      if(!req.randomize() with { tlast == (i==4); }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_009: TWAKEUP asserted 3 cycles before TVALID
class axi_stream_master_tc_mst_009_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_009_seq)
  function new(string name = "axi_stream_master_tc_mst_009_seq"); super.new(name); endfunction
  task body();
    repeat(10) begin
      req = axi_stream_master_seq_item::type_id::create("req");
      start_item(req);
      if(!req.randomize() with { twakeup_early == 3; }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_010: Negative - TDATACHK parity corruption
class axi_stream_master_tc_mst_010_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_010_seq)
  function new(string name = "axi_stream_master_tc_mst_010_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { corrupt_parity == 1; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_011: Parity corruption on TLASTCHK
class axi_stream_master_tc_mst_011_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_011_seq)
  function new(string name = "axi_stream_master_tc_mst_011_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { tlast == 1; corrupt_parity == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_012: Max latency TREADY
class axi_stream_master_tc_mst_012_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_012_seq)
  function new(string name = "axi_stream_master_tc_mst_012_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    req.c_delay.constraint_mode(0);
    start_item(req);
    if(!req.randomize() with { delay_cycles == 50; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_013: Valid transfers with correct ODD parity
class axi_stream_master_tc_mst_013_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_013_seq)
  function new(string name = "axi_stream_master_tc_mst_013_seq"); super.new(name); endfunction
  task body();
    repeat(20) begin
      req = axi_stream_master_seq_item::type_id::create("req");
      start_item(req);
      if(!req.randomize() with { corrupt_parity == 0; corrupt_tdata == 0; }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_014: Negative - TDATA Bit-flip Parity Error
class axi_stream_master_tc_mst_014_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_014_seq)
  function new(string name = "axi_stream_master_tc_mst_014_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { corrupt_tdata == 1; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_015: Reset exit and first TVALID
class axi_stream_master_tc_mst_015_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_015_seq)
  function new(string name = "axi_stream_master_tc_mst_015_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { delay_cycles == 0; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_016: TREADY deasserted mid-packet hold check
class axi_stream_master_tc_mst_016_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_016_seq)
  function new(string name = "axi_stream_master_tc_mst_016_seq"); super.new(name); endfunction
  task body();
    for (int i=0; i<10; i++) begin
      req = axi_stream_master_seq_item::type_id::create("req");
      start_item(req);
      if(!req.randomize() with { tlast == (i==9); }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_017: Unaligned Packet START
class axi_stream_master_tc_mst_017_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_017_seq)
  function new(string name = "axi_stream_master_tc_mst_017_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { tkeep == 4'b0111; tlast == 0; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
    req = axi_stream_master_seq_item::type_id::create("req_done");
    start_item(req);
    if(!req.randomize() with { tkeep == 4'b1111; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_018: Unaligned Packet END
class axi_stream_master_tc_mst_018_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_018_seq)
  function new(string name = "axi_stream_master_tc_mst_018_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { tkeep == 4'b1111; tlast == 0; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
    req = axi_stream_master_seq_item::type_id::create("req_done");
    start_item(req);
    if(!req.randomize() with { tkeep == 4'b0011; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_019: Special Case - All Position Bytes
class axi_stream_master_tc_mst_019_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_019_seq)
  function new(string name = "axi_stream_master_tc_mst_019_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { tkeep == 4'b1111; tstrb == 4'b0000; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_020: High volume stress test
class axi_stream_master_tc_mst_020_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_020_seq)
  function new(string name = "axi_stream_master_tc_mst_020_seq"); super.new(name); endfunction
  task body();
    repeat(1000) begin
      req = axi_stream_master_seq_item::type_id::create("req");
      start_item(req);
      if(!req.randomize()) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_021: Mid-burst reset
class axi_stream_master_tc_mst_021_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_021_seq)
  function new(string name = "axi_stream_master_tc_mst_021_seq"); super.new(name); endfunction
  task body();
    for (int i=0; i<5; i++) begin
      req = axi_stream_master_seq_item::type_id::create("req");
      start_item(req);
      if(!req.randomize() with { tlast == 0; }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_022: sideband integrity - TUSER with TKEEP=0
class axi_stream_master_tc_mst_022_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_022_seq)
  function new(string name = "axi_stream_master_tc_mst_022_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { tkeep == 4'b0000; tuser == 4'hA; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_023: Frame of exactly 8 packets
class axi_stream_master_tc_mst_023_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_023_seq)
  function new(string name = "axi_stream_master_tc_mst_023_seq"); super.new(name); endfunction
  task body();
    for (int p=0; p<8; p++) begin
      req = axi_stream_master_seq_item::type_id::create($sformatf("pkt_%0d", p));
      start_item(req);
      if(!req.randomize() with { tlast == 1; }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_024: TWAKEUP + TVALID simultaneous
class axi_stream_master_tc_mst_024_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_024_seq)
  function new(string name = "axi_stream_master_tc_mst_024_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { twakeup_early == 0; delay_cycles == 0; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_025: Valid drop before Ready (negative)
class axi_stream_master_tc_mst_025_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_025_seq)
  function new(string name = "axi_stream_master_tc_mst_025_seq"); super.new(name); endfunction
  task body();
    req = axi_stream_master_seq_item::type_id::create("req");
    start_item(req);
    if(!req.randomize() with { drop_valid_early == 1; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
    finish_item(req);
  endtask
endclass

// TC_MST_026: Full 8-bit TID Sweep
class axi_stream_master_tc_mst_026_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_026_seq)
  function new(string name = "axi_stream_master_tc_mst_026_seq"); super.new(name); endfunction
  task body();
    for (int id=0; id<256; id++) begin
      req = axi_stream_master_seq_item::type_id::create($sformatf("tid_%0d", id));
      start_item(req);
      if(!req.randomize() with { tid == id; tlast == 1; }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass

// TC_MST_027: Random packet length
class axi_stream_master_tc_mst_027_seq extends axi_stream_master_base_seq;
  `uvm_object_utils(axi_stream_master_tc_mst_027_seq)
  function new(string name = "axi_stream_master_tc_mst_027_seq"); super.new(name); endfunction
  task body();
    int len = $urandom_range(1, 256);
    for (int i=0; i<len; i++) begin
      req = axi_stream_master_seq_item::type_id::create($sformatf("beat_%0d", i));
      start_item(req);
      if(!req.randomize() with { tlast == (i == len-1); }) `uvm_error("SEQ", "Rand failed")
      finish_item(req);
    end
  endtask
endclass
