// AXI-Stream Slave VIP Top-Level Testbench
// DUT = Behavioral AXI-Stream Master BFM (Transmitter)
// VIP = Slave (Receiver) — drives TREADY + TREADYCHK
`timescale 1ns/1ps
`include "axi_stream_slave_vip_defines.sv"

// ── AXI-Stream Master BFM (acts as DUT Master / Transmitter) ─────────────────
module axi_stream_master_bfm (
  input  bit                       ACLK,
  input  logic                     ARESETn,
  input  logic                     TREADY,
  output logic                     TVALID,
  output logic [`TDATA_WIDTH-1:0]  TDATA,
  output logic [`TDATA_WIDTH/8-1:0] TKEEP,
  output logic [`TDATA_WIDTH/8-1:0] TSTRB,
  output logic                     TLAST,
  output logic [`TID_WIDTH-1:0]    TID,
  output logic [`TDEST_WIDTH-1:0]  TDEST,
  output logic [`TUSER_WIDTH-1:0]  TUSER,
  output logic                     TWAKEUP,
  // AXI5 check signals generated by DUT Master
  output logic [`TDATA_WIDTH/8-1:0] TDATACHK,
  output logic                     TVALIDCHK,
  output logic                     TLASTCHK,
  output logic                     TWAKEUPCHK
);

  // ── Odd parity helpers ───────────────────────────────────────────────────────
  function automatic logic byte_odd_par(logic [7:0] b);
    return ~^b;
  endfunction

  // ── Internal BFM state ───────────────────────────────────────────────────────
  logic [`TDATA_WIDTH-1:0]  data_reg;
  logic [`TDATA_WIDTH/8-1:0] keep_reg, strb_reg;
  logic                     last_reg;
  logic [`TID_WIDTH-1:0]    tid_reg;
  logic [`TDEST_WIDTH-1:0]  dest_reg;
  logic [`TUSER_WIDTH-1:0]  user_reg;
  int  beat_cnt  = 0;
  int  pkt_len   = 8;  // default packet length (changes per packet)
  int  pkt_num   = 0;

  // Drive outputs combinatorially from registers
  assign TVALID    = (ARESETn === 1'b1) ? 1'b1 : 1'b0;
  assign TDATA     = data_reg;
  assign TKEEP     = keep_reg;
  assign TSTRB     = strb_reg;
  assign TLAST     = last_reg;
  assign TID       = tid_reg;
  assign TDEST     = dest_reg;
  assign TUSER     = user_reg;
  assign TWAKEUP   = (ARESETn === 1'b1) ? 1'b1 : 1'b0;  // always asserted

  // AXI5 parity (computed continuously)
  assign TDATACHK  = {byte_odd_par(data_reg[31:24]),
                      byte_odd_par(data_reg[23:16]),
                      byte_odd_par(data_reg[15:8]),
                      byte_odd_par(data_reg[7:0])};
  assign TVALIDCHK  = ~TVALID;   // odd parity of 1-bit
  assign TLASTCHK   = ~TLAST;    // odd parity of 1-bit
  assign TWAKEUPCHK = ~TWAKEUP;  // odd parity of 1-bit

  // ── BFM Sequencing ───────────────────────────────────────────────────────────
  initial begin
    data_reg = 0;
    keep_reg = {(`TDATA_WIDTH/8){1'b1}};  // all bytes active
    strb_reg = {(`TDATA_WIDTH/8){1'b1}};
    last_reg = 0;
    tid_reg  = 0;
    dest_reg = 0;
    user_reg = 0;
  end

  always @(posedge ACLK) begin
    if (ARESETn === 1'b0) begin
      // During reset: TVALID driven LOW (done via assign), registers reset
      data_reg <= 0;
      keep_reg <= {(`TDATA_WIDTH/8){1'b1}};
      strb_reg <= {(`TDATA_WIDTH/8){1'b1}};
      last_reg <= 0;
      tid_reg  <= 0;
      dest_reg <= 0;
      user_reg <= 0;
      beat_cnt <= 0;
      pkt_num  <= 0;
      pkt_len  <= 8;
    end else begin
      // Handshake: advance to next beat
      if (TVALID && TREADY) begin
        beat_cnt <= beat_cnt + 1;
        data_reg <= data_reg + 1;

        if (last_reg) begin
          // End of packet — start new packet
          beat_cnt <= 0;
          pkt_num  <= pkt_num + 1;
          // Rotate packet length: 1,4,8,16,32,64,1,...
          case (pkt_len)
            1:  pkt_len <= 4;
            4:  pkt_len <= 8;
            8:  pkt_len <= 16;
            16: pkt_len <= 32;
            32: pkt_len <= 64;
            default: pkt_len <= 1;
          endcase
          // Rotate TID 0→1→2→3→0
          tid_reg <= (tid_reg == 4'd3) ? 0 : tid_reg + 1;
          last_reg <= (pkt_len == 1);  // next packet length 1 → TLAST immediately
        end else begin
          last_reg <= (beat_cnt + 1 == pkt_len - 1);
        end
      end else if (!TVALID) begin
        // TVALID deasserted (only during reset, handled above)
        last_reg <= (pkt_len == 1);
      end
    end
  end

endmodule

// ── Top-Level Testbench Module ────────────────────────────────────────────────
module axi_stream_slave_vip_tb_top;
  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import axi_stream_slave_vip_pkg::*;

  // ── Clock ─────────────────────────────────────────────────────────────────────
  bit ACLK;
  initial ACLK = 0;
  always #(`CLK_PERIOD/2) ACLK = ~ACLK;

  // ── Interface ─────────────────────────────────────────────────────────────────
  axi_stream_slave_vip_if vif (.ACLK(ACLK));

  // ── DUT Master BFM ───────────────────────────────────────────────────────────
  axi_stream_master_bfm dut_master (
    .ACLK       (ACLK),
    .ARESETn    (vif.ARESETn),
    .TREADY     (vif.TREADY),
    .TVALID     (vif.TVALID),
    .TDATA      (vif.TDATA),
    .TKEEP      (vif.TKEEP),
    .TSTRB      (vif.TSTRB),
    .TLAST      (vif.TLAST),
    .TID        (vif.TID),
    .TDEST      (vif.TDEST),
    .TUSER      (vif.TUSER),
    .TWAKEUP    (vif.TWAKEUP),
    .TDATACHK   (vif.TDATACHK),
    .TVALIDCHK  (vif.TVALIDCHK),
    .TLASTCHK   (vif.TLASTCHK),
    .TWAKEUPCHK (vif.TWAKEUPCHK)
  );

  // ── Reset sequencing ──────────────────────────────────────────────────────────
  initial begin
    vif.ARESETn = 1'b0;
    repeat (5) @(posedge ACLK);
    @(negedge ACLK);
    vif.ARESETn = 1'b1;
    `uvm_info("TB_TOP", "ARESETn deasserted — DUT Master may now assert TVALID", UVM_NONE)
  end

  // ── UVM ConfigDB: push VIF into the test ─────────────────────────────────────
  initial begin
    uvm_config_db #(virtual axi_stream_slave_vip_if)::set(
      null, "uvm_test_top", "vif", vif);
    run_test();
  end

endmodule
